### ISSUE TITLE
Timeline feedback

### ISSUE THREAD

**Issue by wolverdude** [iannguyen/Capstone-RateMyWizards#1]
Your MVP features look good. Good job keeping it minimal!

Your first week is a bit ambitious. I would suggest padding your estimates a little.

Make sure you don't implement the _whole_ JSON API the first day. Only implement the parts of the API and schema that you need for this step because you're likely to see things that need to be changed/tweaked as you go along, and you don't want to waste the work of creating an API you won't use, maybe even leaving that cruft in the codebase for someone to stumble upon in a few months and wonder what it's there for... or for hackers to stumble upon and decide what it's there for.

Don't put CSS off until the end. Whatever you schedule last, you risk not doing at all. You have wireframes. Implement them. It's better to have a less feature-full app that looks nice than to have a fully-featured site that looks like it was designed in the nineties. Looks impress.

**Comment by iannguyen** [comment]
Added an extra day to Phase 1 and Phase 3, to allow for styling. Splitting JSON API for professors and reviews respectively.
