### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by wolverdude** [iannguyen/Capstone-RateMyWizards#2]
You don't need `image_content_type` or `image_file_size`. When in doubt, don't add columns. You can always add needed columns later, but removing unnecessary columns is dangerous, so people usually just leave them there, confusing whoever is trying to learn the schema with distracting, superfluous data. This is especially annoying with `NOT NULL` columns.

You don't need `image_updated_at` either, but for the record, it should be a `timestamp`, not a `string`.

**Comment by iannguyen** [comment]
Thank you for clarifying this. Removed unnecessary columns. Will still plan to add image uploading in bonus phase except for House and Professor seed data.
