### ISSUE TITLE
Component Feedback

### ISSUE THREAD

**Issue by wolverdude** [iannguyen/Capstone-RateMyWizards#3]
- I would suggest including a nav bar. It's something people have come to expect from every site, and an easy way to (or fail to) impress.
- Your component hierarchy doesn't match your mockups. Lines shouldn't indicate links, they should indicate nesting. It's also not clear that the houses index and search bar are on the same page.

**Comment by iannguyen** [comment]
Moved logo to center and will plan to have it link to the Root/Home Page. Replaced top left link with a 'back' link. A little bit unclear on the structure of the component hierarchy, so please let me know it is still not done correctly. Thanks for the feedback John.
